preconnect:
  - https://gcore.jsdelivr.net
  - https://unpkg.com
  - https://cdn.bootcdn.net

inject:
  head:
    - <link rel="apple-touch-icon" sizes="180x180" href="/assets/favicon/apple-touch-icon.png">
    - <link rel="icon" type="image/png" sizes="32x32" href="/assets/favicon/favicon-32x32.png">
    - <link rel="icon" type="image/png" sizes="16x16" href="/assets/favicon/favicon-16x16.png">
    - <link rel="manifest" href="/assets/favicon/site.webmanifest">
    - <link rel="shortcut icon" href="/assets/favicon/favicon.ico">
    - <meta name="theme-color" content="#f8f8f8">
    - <link rel="stylesheet" href="https://cdn.bootcdn.net/ajax/libs/lxgw-wenkai-screen-webfont/1.7.0/style.min.css" media="all" />

######## Sidebar ########
# 左上角显示的 logo 区域，包含图标、大标题、副标题

logo:
  icon: /assets/avatar/avatar.svg
  title: Leohoo
  subtitle: '记录生活、瞎折腾 | Record life, mess around'

# 侧边栏主功能导航菜单
menubar:
  columns: 4 # 一行多少个
  # id: 页面中高亮的 menu_id 
  # theme: 高亮时的颜色，仅 svg 中 fill="currentColor" 时有效
  # icon: 支持 svg/img 标签，可以定义在 icons.yml 文件中，也支持外部图片的 URL
  # title: 标题
  # url: 点击跳转到哪，支持相对路径和绝对路径
  items: 
    - id: post
      theme: '#1BCDFC'
      icon: solar:documents-bold-duotone
      title: 博客
      url: /
    - id: topic
      theme: '#3DC550'
      icon: solar:notebook-bookmark-bold-duotone
      title: 专栏
      url: /topic/
    - id: explore
      theme: '#FA6400'
      icon: solar:planet-bold-duotone
      title: 探索
      url: /explore/
    - id: social
      theme: '#F44336'
      icon: solar:chat-square-like-bold-duotone
      title: 社交
      url: /friends/

######## Main ########
# 站点主结构树

site_tree:
  #  -- 列表类页面 -- #
  # 主页配置
  home:
    sidebar: starter, welcome, recent
  index_blog:
    sidebar: starter, welcome, recent
  index_topic:
    menu_id: topic
  topic:
    menu_id: topic

article:
  share: [wechat, weibo, email, link]


style:
  text-align: justify
  smooth_scroll: false
  codeblock:
    scrollbar: 0px
  font-size:
    body: 1rem
  font-family:
    logo: '"LXGW WenKai Screen", system-ui, "Microsoft Yahei", "Segoe UI", -apple-system, Roboto, Ubuntu, "Helvetica Neue", Arial, "WenQuanYi Micro Hei", sans-serif'
    body: '"LXGW WenKai Screen", system-ui, "Microsoft Yahei", "Segoe UI", -apple-system, Roboto, Ubuntu, "Helvetica Neue", Arial, "WenQuanYi Micro Hei", sans-serif'
    code: '"LXGW WenKai Screen", Menlo, Monaco, Consolas, system-ui, "Courier New", monospace, sans-serif'
    codeblock: 'Menlo, Monaco, Consolas, system-ui, "Courier New", monospace, sans-serif'